### ISSUE TITLE
恳请添加使用教程

### ISSUE THREAD

**Issue by FinBird** [fengberd/YuRISTools#1]
首先感谢大大写的这个工具，本人找人帮忙编译本项目后，顺利对“夏之锁”的.ypf中解得了图像之类的资源。
但在处理YSTB（剧本文件）时，package.json和ouput_path之类的路径尝试了几个东西都报错了。
最要命的是不懂C#。。。希望能从大大这里得到帮助，谢谢

**Comment by fengberd** [comment]
之前发给另外一位的
如果加密了 你得去游戏程序里找YSTB解密 Key
没有翻译 我假设你看得懂英文
https://t.me/s/yuris_tools_temp

**Comment by FinBird** [comment]
感谢大大，以后有空会试着仿造着写个Python的玩玩
