### ISSUE TITLE
解包夏之锁时出现错误

### ISSUE THREAD

**Issue by Isayama-Kagura** [fengberd/YuRISTools#2]
![oops](https://user-images.githubusercontent.com/30114848/111019453-4ce3eb00-83fa-11eb-9029-29ff3b68c8a7.png)

如图，解到ed.ypf时会出现无法解压的情况，是什么原因呢？

另外，可以的话，能大概说一下magic32 key能在什么位置找到吗，本人逆向菜鸟，希望大佬能指教一下

**Comment by fengberd** [comment]
这个文件大概率不是真正的 ypf 而是媒体文件，尝试使用 binwalk/file/DIE 进行分析，请不要过于依赖后缀名
Key 需要在 IDA 里追解密逻辑，一两句话说不清，我没有精力提供此类支持
