### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by 0xh3LL0** [fengberd/YuRISTools#3]
[log.txt](https://github.com/fengberd/YuRISTools/files/6226070/log.txt)

i dont have vs installed and only use msbuild (from net framework)
also change net 4.5 to 4.6

**Comment by fengberd** [comment]
The error log is telling you what to do itself...
If you're unable to get the environment installed properly, try to build with Visual Studio 2019 and default `.NET Desktop Development` installation.
```
Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons.
```
```
The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.
```

I think you can't build, or can't build easily, a simple C# project created by Visual Studio without installing those toolsets. Checkout the VS installer, there're a hell lot of packages required.
